eureka:
  client:
    serviceUrl:
       defaultZone: http://192.168.3.208:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8762
  
spring:
  application:
    name: eshop-product-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.3.205:3306/eshop
#    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: root
  rabbitmq:
#    host: localhost
    host: 192.168.3.205
    port: 5672  
    username: rabbitadmin  
    password: 123456